apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak-redirect-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak-redirect-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "keycloak-redirect-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
