apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-redirect-controller.fullname" . }}-config
  labels:
    {{- include "keycloak-redirect-controller.labels" . | nindent 4 }}
data:
  config.toml: |-
{{ .Values.config | indent 4 }}
